### ISSUE TITLE
TypeError: must be str, not bytes in Python 3

### ISSUE THREAD

**Issue by asmeurer** [mk-fg/pretty-yaml#11]
```
In [7]: pyaml.pprint("a")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-768996862cc6> in <module>()
----> 1 pyaml.pprint("a")

/Users/aaronmeurer/Documents/pretty-yaml/pyaml/__init__.py in pprint(*data, **dump_kws)
    169         dst = dump_kws.pop('file', dump_kws.pop('dst', sys.stdout))
    170         if len(data) == 1: data, = data
--> 171         dump(data, dst=dst, **dump_kws)
    172
    173 p, _p = pprint, print

/Users/aaronmeurer/Documents/pretty-yaml/pyaml/__init__.py in dump(data, dst, safe, force_embed, vspacing, string_val_style)
    161                 return buff.getvalue().decode('utf-8')
    162         else:
--> 163                 dst.write(buff.getvalue())
    164
    165 def dumps(data, **dump_kws):

TypeError: must be str, not bytes
```

**Comment by mk-fg** [comment]
As noted in the [Installation section](https://github.com/mk-fg/pretty-yaml#installation), Python-3.X is just not supported.

I think there were reports (in the closed issues/PRs) that the module works with 3.X after 2to3, but I'm not sure, never tried that myself, I'm afraid, don't use 3.X here at all (yet?).

**Comment by asmeurer** [comment]
Are there at least plans to support it? These days I consider anything that doesn't support Python 3 to be a dead project.

**Comment by mk-fg** [comment]
While it's nowhere near the effort of porting and maintaining a separate version in a language you don't care much about (e.g. COBOL), I'm afraid I still don't have any plans to do it, sorry.
