### ISSUE TITLE
Serialization bug

### ISSUE THREAD

**Issue by mpenkov** [mk-fg/pretty-yaml#13]
Given the data:

    {'foo': ['bar:', 'baz']}

pyaml serializes this as:

    foo:
      - bar:
      - baz

which then gets deserialized by yaml as:

    {'foo': [{'bar': None}, 'baz']}

This is different to the original data. I'm not sure if this is a problem with pyaml, yaml, or something else. The problem is fixed by forcing quotes around "bar:" in the output:

    foo:
      - "bar:"
      - baz

This can be achieved by:

    pyaml.dump(data, stream, string_val_style="double-quoted")

Sample code to reproduce the problem:

```
import yaml
import pyaml
import StringIO
data = {"foo": ["bar:", "baz"]}
print data
stream = StringIO.StringIO()
pyaml.dump(data, stream)
print stream.getvalue()
data2 = yaml.load(stream.getvalue())
print data2
```

**Comment by mk-fg** [comment]
It's definitely a pyaml issue, as PyYAML does the conservative thing and quotes as much as possible, which pyaml tries to "fix", in it's deeply flawed and hacky way ;)

Should be fixed in a77add9, thanks for pointing it out!
