### ISSUE TITLE
Two problems converting AWS Cloudformation templates

### ISSUE THREAD

**Issue by vt102** [mk-fg/pretty-yaml#19]
AWS CloudFormation templates now support YAML, and we're converting a lot of JSON using pyaml and enjoy it, but for one thing:

~~~
                        "Value": {
                            "Fn::Join": [
                                "",
                                [
                                    "apac-",
                                    {
                                        "Ref": "Environment"
                                    },
                                    "-",
                                    {
                                        "Ref": "EnvironmentName"
                                    },
                                    "-",
~~~

Here is what the above translates to (via print pyaml.dump(json.load(sys.stdin))):

~~~
          Value:
            Fn::Join:
              -
              - - apac-
                - Ref: Environment
                - -
                - Ref: EnvironmentName
                - -
~~~

There are two problems.  The first, we need an empty string as the value after "Fn::Join".  This may not be a problem with YAML, but AWS won't accept it-- it would be nice to have an option to print empty strings.

The second I think may be a bug-- the lines that read "- -" need the second dash in quotes to clarify that it's not a YAML formatting mark, but actually content.

To use these, we have to manually change to the following:

~~~
          Value:
            Fn::Join:
              - ''
              - - apac-
                - Ref: Environment
                - '-'
                - Ref: EnvironmentName
                - '-'
~~~

**Comment by mk-fg** [comment]
Yeah, I think these kind of corner cases is why PyYAML does things the way it does - it might not be pretty, but reliable and accounts for everything.

Thanks for reporting.
Might fix these sometime later, should be just a matter of adding two checks/special-cases in existing string dump method, i think.

**Comment by mk-fg** [comment]
Finally got around to looking into it, and fixed it simply by adding empty and single-dash strings to style=literal exceptions, as these should be quoted in all contexts anyway, I think (i.e. `key: -` isn't valid either).
