### ISSUE TITLE
Default to safe=True?

### ISSUE THREAD

**Issue by ypid** [mk-fg/pretty-yaml#21]
Currently, [`pyaml.dump`](https://github.com/mk-fg/pretty-yaml/blob/47329c7c62be545ad52e5e4d657303d8c88f7e9e/pyaml/__init__.py#L159) defaults to `safe=False`. Maybe it could be changed to `safe=True` by default ([security by default](https://en.wikipedia.org/wiki/Secure_by_default))?

Would there be any noticeable difference from that and do you think `safe=True` would limit normal use cases?

If you disagree with changing the default, maybe the docs can be updated to use the `safe=True` where possible?

See also: [Make load safe_load](https://github.com/yaml/pyyaml/issues/5)

Thanks for your nice library!

**Comment by mk-fg** [comment]
Hi, thanks for comment, but are you sure `safe=True` is about security?

**Comment by mk-fg** [comment]
Iirc it makes pyyaml output as simple types as possible, so that even dumbest stripped-down parsers can read it, i.e. "safe" in a "most compatible" sense.

**Comment by mk-fg** [comment]
Which, iirc also makes resulting YAML as ugly as possible, which clearly contradicts the goal of the module.

**Comment by mk-fg** [comment]
Also, totally agree on load vs safe_load, always use the latter myself, but don't think it's related, though will need to check it, not 100% sure.

**Comment by ypid** [comment]
> Hi, thanks for comment, but are you sure safe=True is about security?

I don’t really think so. The issues with unsafe load are much more severe.

**Comment by mk-fg** [comment]
> I don’t really think so. The issues with unsafe load are much more severe.

But this module doesn't do loading at all! ;)

**Comment by ypid** [comment]
> But this module doesn't do loading at all! ;)

Seen that :) I also noticed that you use `safe_load` in your examples. Nicely done :+1:

**Comment by mk-fg** [comment]
Just noticed that `safe=` is actually a flag in pyaml, and I think it's and unfortunately named option, which I've copied from PyYAML's similarly-named safe_dump thing, which does similar "most compatible" output.

pyaml, similarly, uses UnsafePrettyYAMLDumper, which dabbles with scalar and sequence styles, and can occasionally produce broken output, hence the option to avoid it.

Don't think renaming it now is a good idea though, and it's at least somewhat consistent that way, if nothing else, so guess I'll just leave it be.

**Comment by mk-fg** [comment]
Also, PrettyYAMLDumper and co always based on yaml.dumper.SafeDumper, and I dare you to look at the things with exclamation marks non-safe pyyaml dumper produces, it's just ridiculous.

**Comment by ypid** [comment]
Sounds reasonable. Thanks for explaining.
