### ISSUE TITLE
dump fails on numpy arrays

### ISSUE THREAD

**Issue by DSLituiev** [mk-fg/pretty-yaml#24]
I am trying to dump a dictionary with a numpy array. It works with `yaml` package, but fails here with `pyaml`:

```
dd = dict(a="b", b="c", c=(0,1,2), d= np.r_[4,5,6])
print(yaml.dump(dd, default_flow_style=False))
print("-"*20)
print(pyaml.dump(dd))
```

```
...
/usr/local/lib/python3.6/site-packages/pyaml/__init__.py in represent_undefined(dumper, data)
     34                 elif isinstance(data, OrderedDict): return dumper.represent_odict(data)
     35                 elif isinstance(data, dict): return dumper.represent_dict(data)
---> 36                 return super(PrettyYAMLDumper, dumper).represent_undefined(data)
     37 
     38         def serialize_node(self, node, parent, index):

/usr/local/lib/python3.6/site-packages/yaml/representer.py in represent_undefined(self, data)
    227 
    228     def represent_undefined(self, data):
--> 229         raise RepresenterError("cannot represent an object: %s" % data)
    230 
    231 SafeRepresenter.add_representer(type(None),

RepresenterError: cannot represent an object: [4 5 6]
```

**Comment by DSLituiev** [comment]
it might be a general glitch, but for numpy arrays one can implement running `.tolist()` on them before serializing.

**Comment by mk-fg** [comment]
Thanks for the heads-up.

Weird that it works with pyyaml, as it seem to be dispatching these arrays to represent_undefined here, which also falls back to pyyaml's represent_undefined, which doesn't know what to do with these things.

Will probably add a `.tolist()` processing for them here, given that numpy is fairly cornerstone thing in python, indeed, though it general supporting every third-party module datatype out there seems like a bad idea.

**Comment by mk-fg** [comment]
Should work, though guess you've probably moved past it by now, sorry it took that long for no reason.
