### ISSUE TITLE
pyaml not compatible with ruamel.yaml

### ISSUE THREAD

**Issue by StephenBrown2** [mk-fg/pretty-yaml#34]
Given the following test yaml:
```yaml
# This is a commented YAML file
replica: 1

image:
  repository: docker/python
  pull: IfNotPresent

imagePullSecrets:
  - name: docker-secret
```

and the following test python:
```py
#!/usr/bin/env python3
from pathlib import Path
import pyaml
from ruamel.yaml import YAML

yaml = YAML()
test_file = Path("./test.yaml")
test_load = yaml.load(test_file)
pyaml.p(test_load)
```

I get the following error:
```shell
Traceback (most recent call last):
  File "./test_yaml.py", line 9, in <module>
    pyaml.p(test_load)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaml/__init__.py", line 208, in pprint
    dump(data, dst=dst, **dump_kws)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaml/__init__.py", line 188, in dump
    yaml.dump_all( data, buff, Dumper=Dumper,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaml/__init__.py", line 37, in represent_undefined
    elif isinstance(data, OrderedDict): return dumper.represent_odict(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaml/__init__.py", line 29, in represent_odict
    node_value = dumper.represent_data(item_value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaml/__init__.py", line 40, in represent_undefined
    return super(PrettyYAMLDumper, dumper).represent_undefined(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', [ordereddict([('name', 'docker-secret')])])
```

Given that ruamel is mentioned in the docs for parsing, pyaml should be able to handle the results.

The problem is likely that ruamel creates and uses it's own subclass of OrderedDict:

https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/constructor.py#l20

https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/compat.py#l23

pyaml could do something like:

```py
try:
	from ruamel.yaml.compat import ordereddict
	PrettyYAMLDumper.add_representer(ordereddict, PrettyYAMLDumper.represent_odict)
except ImportError:
    pass
```

**Comment by mk-fg** [comment]
Yeah, shouldn't hurt to do such import-check, probably, added it. Thanks!

**Comment by StephenBrown2** [comment]
Wow, thanks for the fast response!

I'm still running into the error, looks like it might be a little more nunanced:

```
yaml.representer.RepresenterError: ('cannot represent an object', [ordereddict([('name', 'docker-secret')])])
```

is referencing

```yaml
imagePullSecrets:
  - name: docker-secret
```

which is actually a list of `ordereddicts`, expanding it looks like:
```
[
	ordereddict(
		[
			('name', 'docker-secret')
		]
	)
]
```

Not sure why it's having trouble with that, but removing that stanza lets it fail on a different one, also a list, but this time of strings:
```yaml
securityContext:
  capabilities:
    drop:
      - ALL
```
gives:
```
yaml.representer.RepresenterError: ('cannot represent an object', ['ALL'])
```

and another:
```yaml
tolerations:
  - effect: NoSchedule
    key: node_role
    operator: Equal
    value: platform_worker
```
gives:
```
yaml.representer.RepresenterError: ('cannot represent an object', [ordereddict([('effect', 'NoSchedule'), ('key', 'node_role'), ('operator', 'Equal'), ('value', 'platform_worker')])])
```

So maybe it's just failing on lists for some reason?

**Comment by mk-fg** [comment]
I did add parsing similar stuff to test and tested with original YAML you gave above, but not exactly same code.
Turns out, difference is that I've used `YAML(typ='safe')`, as that seem to be same as safe_load in PyYAML, and don't think unsafe load should ever work right.
And turns out it doesn't even produce any ordereddict types in there with typ=safe - just uses regular ones.

**Comment by mk-fg** [comment]
Dropped earlier special-case tweak now, and added suggestion to use `YAML(typ='safe')` to README instead.

As mentioned, don't think "unsafe" load (if I understand what it does correctly) should work with this module, as it allows any kind of custom types via arbitrary code execution.

There are probably use-cases for using it, but note that in many common cases it's very much not what you want to do, and allows for easily-explotable security issues by design, unless yaml in question is some kind of static file comitted alongside code (e.g. definition of something) and can only be edited using same capabilities as editing code next to it.

And another two reasons for not bothering to support this use-case here:
- Would be nice to avoid "import" for a random third-party module, like ruamel.yaml in this case.
- I'm lazy to figure out how to do it too :)

If you can make a PR that'd implement it somehow, and ideally won't always be importing ruaml.yaml - let me know, can probably merge it.

**Comment by StephenBrown2** [comment]
Well, `typ='safe'` works, but loses all ordering. Telling pyaml to `sort_dicts=False` resolves that, but still loses comments, which I can live with.
Looks like it should be good then, I wouldn't really want unsafe loading either.
I just updated to 20.3.1, and it all works as expected, so thanks again!

**Comment by mk-fg** [comment]
Oh yeah, would be really nice if it didn't loose the comments with ruamel.yaml, but I think at the point where you want to output exactly same thing as parsed with same comments and indents and such, you'd probably want to use dumper in ruamel.yaml, and not maintain parallel implementation here.

**Comment by StephenBrown2** [comment]
Could you suggest a set of human-friendly representation options for ruamel.yaml like you do with pyyaml? No worries if not, it's not the focus of this project.

**Comment by mk-fg** [comment]
Don't think I can.

When I used it for setting values in exising config, didn't bother with export and simply updated numbers/strings at a position where ruamel.yaml said they were in the source file, to easily avoid any re-formatting that way.

Only needed to update single and simple values that way though.
Should be impractical to do that with more complex values or changes.
