### ISSUE TITLE
openapi.yaml is invalid after re-formatting

### ISSUE THREAD

**Issue by chbndrhnns** [mk-fg/pretty-yaml#35]
I tried to apply the formatter to an OpenAPI spec, ([ex1](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml). 

It appears to me that after running `python -m pyaml -r ./juice_users/openapi/openapi.yaml`, the spec is broken and cannot be used anymore with the OpenAPI generator.

Is there something I could do to prevent breaking my spec file?

**Comment by mk-fg** [comment]
I think the issue you're referring to is with the lines like this one:
```$ref: "#/components/schemas/Error"```

Where pyaml, trying to keep unnecessary quotes out of strings if possible, did not have detection for this "will end up being comment" case, hence the breakage.

Fixed it in f904b96 and 20.4.0 by checking for "#" anywhere within strings to use quoted style for those that have it.

Let me know if you might've meant some other issue there.
Though note that this module is not really intended for producing correct output (as should be also mentioned in the README), just something readable that looks like more-or-less correct YAML, so probably should not be used to serialize data for other scripts to parse, only for humans. 

Thanks for reporting!

**Comment by chbndrhnns** [comment]
My intention was to use it as kind of a formatting tool that I can run on the files so that developers do not need to take care for formatting. Let's see how it goes!
