### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by polyzen** [mk-fg/pretty-yaml#45]
Tedious to find what's changed between releases without tags. For example, I used Git blame on the version key in your pyproject.toml to find what commits matched which release, and then copy and pasted those commits to get the Git log of changes.

We (at Arch Linux) also want to move to using untouched sources (eg. PyPI releases might contain pre-generated contents), and it would be much easier to point at a release tag rather than digging up the commit. https://github.com/mk-fg/pretty-yaml/tags.atom (and releases.atom if you go that route as well) would also become another way of tracking releases.

**Comment by mk-fg** [comment]
Yeah, should probably add a simple git hook to tag stuff from pyproject.toml version changes.

**Comment by mk-fg** [comment]
Added hook for doing that in last minor update, should hopefully do that reliably enough.
Thanks for bringing it up.
